export const columns = [
    {
      field: "sl_no",
      headName: "Serial No.",
      width: 70,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "business_code",
      headName: "Business Code",
      width: 100,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "cust_number",
      headName: "Customer No",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "clear_date",
      headName: "Clear Date",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "business_year",
      headName: "Business Year",
      width: 100,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "doc_id",
      headName: "Document ID",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "posting_date",
      headName: "Posting Date",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "document_create_date",
      headName: "Document Create Date",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "document_create_date_1",
      headName: "Document Create Date.1",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "due_in_date",
      headName: "Due Date",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "invoice_currency",
      headName: "Invoice Currency",
      width: 70,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "document_type",
      headName: "Document Type",
      width: 70,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "posting_id",
      headName: "Posting ID",
      width: 50,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "total_open_amount",
      headName: "Total Open Amount",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "baseline_create_date",
      headName: "Baseline Create Date",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "cust_payment_terms",
      headName: "Customer Payment Terms",
      width: 100,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "invoice_id",
      headName: "Invoice ID",
      width: 150,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "isOpen",
      headName: "Open invoice",
      width: 70,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "aging_bucket",
      headName: "Aging Bucket",
      width: 70,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
    {
      field: "is_deleted",
      headName: "Deleted",
      width: 70,
      headerClassName: "super-app-theme--header",
      headerAlign: "center",
    },
  ];